### ISSUE TITLE
Feature request: Ability to extract the local part and domain from an email address

### ISSUE THREAD

**Issue by jpgoldberg** [johnstonskj/rust-email_address#1]
Thank you so much for building your parser from the RFC specifications. This is very much what I've been looking for.

I would very much like to have the ability to extract the local part and the domain from a syntactically valid address.

**Comment by johnstonskj** [comment]
See commit 1d303455e38bb674c0a7cd48b3e2fcd7d78744b0

**Comment by johnstonskj** [comment]
Included in release 0.2.1
