### ISSUE TITLE
Wrap `Cow` instead of `String`

### ISSUE THREAD

**Issue by uklotzde** [johnstonskj/rust-email_address#12]
To enable some optimizations it would be desirable to wrap `Cow<'a, str>` instead of a `String`. The latter is always owned and needs to be allocated even if the `&str` input could be re-used. An owned e-mail address would then become `EmailAddress<'static>` as a special case.

**Comment by johnstonskj** [comment]
This correct, but for a lot of clients the propagation of the lifetime is now an issue.
