### ISSUE TITLE
Add support for parsing email including name

### ISSUE THREAD

**Issue by ghandic** [johnstonskj/rust-email_address#14]
I would expect during parsing we could extract the display name, similar to how we extract local_part and domain, such that the following would work:

```rust
use std::str::FromStr;
use email_address::EmailAddress;

fn main() {
    let email = "art@vandelay.com";
    let addr = EmailAddress::from_str(email).unwrap();
    println!("{:?}", addr);


    let email2 = "Art Vandelay <art@vandelay.com>";
    let addr2 = EmailAddress::from_str(email2).unwrap();
    println!("{:?}", addr2);
}
```

Current output:

```txt
EmailAddress("art@vandelay.com")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidCharacter', src/main.rs:11:48
```

**Comment by ghandic** [comment]
Preface for this: We are considering crates for use in Pydantic v2, and this is one of the ones being considered in https://github.com/pydantic/pydantic-core/issues/385

**Comment by johnstonskj** [comment]
Thanks for the pull request, this is a great enhancement, it wasn't necessary for what I needed at the time I wrote it but it definitely helps a lot!

**Comment by madkinsz** [comment]
Just following along here, but the validation tests that Pydantic mentions as a reference are for a Python equivalent `python-email-validator` and are available at https://github.com/JoshData/python-email-validator/blob/main/tests/test_syntax.py

**Comment by mplanchard** [comment]
I just wanted to note that if this is added, it would be nice if there were an option to _not_ consider a string like `Matthew Planchard <matthew@mydomain.com>` a valid email, also. There are cases where the difference is meaningful between "anything that could go in an address header" and "something most APIs would accept as an email address," and it would be nice to be able to distinguish between the two, even as e.g. separate types.

**Comment by johnstonskj** [comment]
Have added the flag `allow_display_name` to the `Option` structure in 7b30e9c. Will be a part of 0.1.7.
