### ISSUE TITLE
Controversial UTF-8 characters

### ISSUE THREAD

**Issue by 1oglop1** [johnstonskj/rust-email_address#21]
Hi, I was comparing this crate with `validator` crate, you mentioned in #16.

And I have an email with a controversial character � - https://en.wikipedia.org/wiki/Specials_(Unicode_block) 
Then email_address and validator do not agree if it is valid or not`abc�def@example.com` 

```
let email = "abc�def@example.com";
EmailAddress::from_str(email).is_ok(); // true
validator::validate_email(email);  // false
```

At the moment this crate allows valid email with UTF8 - I guess that's according to
* https://datatracker.ietf.org/doc/html/rfc6531#section-3.2
* https://en.wikipedia.org/wiki/Email_address#Local-part 

perhaps this could be part of `parse_with_options` suggested in #20. 

Probably the best thing for the community would be to have just one crate for email validation.

**Comment by johnstonskj** [comment]
This is a defect. The `is_uchar` test was way to permissive. Have replaced it with `is_utf8_non_ascii` as it should be. Release soon.

**Comment by johnstonskj** [comment]
See release 0.2.9
