### ISSUE TITLE
EmailAddress::is_valid returns true for 'invalid@domain' which is missing a valid top level domain or TLD.

### ISSUE THREAD

**Issue by devrobertpalmer** [johnstonskj/rust-email_address#23]
EmailAddress::is_valid returns true for 'invalid@domain' which is missing a valid top level domain or TLD.  'domain' is not a valid TLD according to [the list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) from IANA.  Would you please add this to your suite of unit tests?

Thanks!

**Comment by mawoka-myblock** [comment]
Having the same problem, as `testdsads@asdas-` isn't a valid email address for sure.

**Comment by gene-hightower** [comment]
What about “jsmith@[any-poop-at-all]” which is acceptable by the syntax of RFC-5322, but is not a useable email address.
The basic issue is that the syntax of email addresses are defined by the ‘Mailbox’ grammar rule from Section 4.1.2 of RFC-5321. <https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.2>. Of course, the domain part is further constrained by the rules of DNS domains.

**Comment by devrobertpalmer** [comment]
I think you are probably right. Would there be value in offering some additional checks for whether an email is deliverable in the public internet?

**Comment by gene-hightower** [comment]
You can check that the Domain part (if not an address-literal) contains at least two labels and the top level contains at least two characters. Any list of valid top-level domains will become obsolete on a regular basis, and naming arrangements can vary.
The domain literal can be a raw IPv4 dotted quad like [192.168.3.4] or an IPv6 address like [IPv6:::1] all that grammar is covered in RFC-5321.

**Comment by blaine-arcjet** [comment]
The examples here should now be able to be configured with v0.2.5 - a bunch of my PRs added options to check these types of things.

**Comment by johnstonskj** [comment]
Also, as @blaine-arcjet has referenced in his test cases, the following is valid `foo@localhost`.

I have added a builder function to the `Option` type that hopefully makes this clear -- `with_required_tld`.

See 6aaec97
