### ISSUE TITLE
Feature request: From<EmailAddress> for String

### ISSUE THREAD

**Issue by sonro** [johnstonskj/rust-email_address#3]
Currently `EmailAddress` is able to convert to a `String` via the `Display` trait.
```rust
// creates a String owned by EmailAddress
let email_addr = EmailAddress::from_str("test@email.com").unwrap();
// creates another string
let email_addr_string = email_addr.to_string();
```

It would be great if there were a way to extract the underlying `String`. I propose implementing the `From` trait to allow for this use case. 
```rust
impl From<EmailAddress> for String {}
```

I will submit a pull request for the change.

**Comment by johnstonskj** [comment]
Thanks, you might also consider adding AsRef<str> if you only need to
borrow the value.

**Comment by sonro** [comment]
Good idea, I will open that as a seperate PR if you don't mind.

**Comment by johnstonskj** [comment]
Sounds great
