### ISSUE TITLE
Manual implementation of Deserialize

### ISSUE THREAD

**Issue by ynuwenhof** [johnstonskj/rust-email_address#5]
The following code will panic when calling `email.local_part()` because the email address stays unchecked during deserialization.

```rs
#[derive(Serialize, Deserialize)]
struct User {
    email: EmailAddress,
}

fn main() -> io::Result<()> {
    let data = r#"{ "email": "userexample.com" }"#;

    let user: User = serde_json::from_str(data)?;
    println!("{}", user.email.local_part());

    Ok(())
}
```

Manually implementing `Deserialize` for `EmailAddress` would catch this error during deserialization.

If this is something that you would like to add, I am happy to open a PR for it.

**Comment by johnstonskj** [comment]
Well that's embarrassing. If you have the time to write the de-serialization I'd be happy to take a PR.
